export enum AssetCommand {
    create = 'create/',
    delete = 'delete/',
    edit = 'edit/',
    view = 'view/',
    detailView = 'detailView/',
    search = 'search/',
    GET_ALL_MODELS = 'assistedmodel/',
    GET_ALL_OWNERS = 'assistedowner/',
    GET_ALL_DATACENTERS = 'assisteddatacenter/',
    GET_ALL_HOSTNAME = 'assistedhostname/',
    UPLOAD_FILE = 'import/',
    EXPORT_FILE = 'export/',
    GET_NEXT_ASSET_NUM = 'nextAssetNumber/',
    GET_NETWORK_NEIGHBORHOOD = "networkNeighborhood/",
}
