export enum AssetInput {
    MODEL = 'model',
    HOSTNAME = 'hostname',
    RACK = 'rack',
    RACK_U = 'rack_position',
    RACK_ORIGINAL = 'rackOriginal',
    RACK_U_ORIGINAL = 'rack_positionOriginal',
    OWNER = 'owner',
    COMMENT = 'comment',
    DATACENTER = 'datacenter_id',
    TAGS = 'tags',
    MAC_ADDRESS = 'mac_address',
    NETWORK_CONNECTIONS = 'network_connections',
    POWER_CONNECTIONS = 'power_connections',
    ASSET_NUMBER = 'asset_number',
    BLADE_CHASSIS = 'blade_chassis',
    BLADE_POSITION = 'blade_position',
}
