repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-byte-order-marker
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

-   repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort

-   repo: https://github.com/asottile/pyupgrade
    rev: v1.26.1
    hooks:
    -   id: pyupgrade

-   repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
    - id: black

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
        - ReactAndFlask/flask-backend/
        - --errors-only
        - --output-format=parseable

    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args:
        - --follow-imports=silent
        - --ignore-missing-imports
