export const testModelArray = [
    {
        'vendor':'a',
        'model_number':'a',
        'height':'a',
        'display_color':'a',
        'ethernet_ports':'a',
        'power_ports':'a',
        'cpu':'a',
        'memory':'a',
        'storage':'a',
        'comments':'a',
    },{
        'vendor':'b',
        'model_number':'b',
        'height':'b',
        'display_color':'b',
        'ethernet_ports':'b',
        'power_ports':'b',
        'cpu':'b',
        'memory':'b',
        'storage':'b',
        'comments':'b',
    },{
        'vendor':'c',
        'model_number':'c',
        'height':'c',
        'display_color':'c',
        'ethernet_ports':'c',
        'power_ports':'c',
        'cpu':'c',
        'memory':'c',
        'storage':'c',
        'comments':'c',
    },
];

export const testUserArray = [
    {
        'username':'a',
        'password':'a',
        'display_name':'a',
        'email':'a',
        'privilege':'a',
    },{
        'username':'b',
        'password':'b',
        'display_name':'b',
        'email':'b',
        'privilege':'b',
    },{
        'username':'c',
        'password':'c',
        'display_name':'c',
        'email':'c',
        'privilege':'c',
    },
];

export const testInstanceArray = [
    {
        'model':'a',
        'hostname':'a',
        'rack':'a',
        'rack_position':'a',
        'owner':'a',
        'comment':'a',
    },{
        'model':'b',
        'hostname':'b',
        'rack':'b',
        'rack_position':'b',
        'owner':'b',
        'comment':'b',
    },{
        'model':'c',
        'hostname':'c',
        'rack':'c',
        'rack_position':'c',
        'owner':'c',
        'comment':'c',
    },
];
